FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY producer.py .

# Notice we don't expose a port here, because the producer only sends data, it doesn't listen!
CMD ["python", "producer.py"]