version: '3.8'

services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    ports:
      - "5001:5001"
    networks:
      - pipeline_network

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - consumer # Wait for the consumer to start before starting the producer
    networks:
      - pipeline_network

networks:
  pipeline_network:
    driver: bridge